# Global defaults for all envs, clusters & apps
helm:
  defaultChartRepo: "oci://charts.company.com/stable"
  defaultChartVersion: "latest"
presets:
  - global-logging
argocd:
  project: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
secrets:
  provider: sops
  key: "arn:aws:kms:us-east-1:123456789012:key/abcdefg"
policies:
  opaBundle: "s3://company-policies/opa-bundle.tar.gz"
metadata:
  labels:
    managed-by: weave-engine
